### ISSUE TITLE
Great app 

### ISSUE THREAD

**Issue by trackermb** [0i0/nonky#2]
Hi there have to say this is great app.  Have a few questions regarding things I would like to be able too.

1. I was was wondering its there a way to have it display horizontal in the middle of the desktop
2. Remove the cryptocurrency or change to GBPxUSD GBPxEuro
3. Font size adjustment

Thanks again

**Comment by 0i0** [comment]
You can code your own visuals
Using HTML5
Check out the README
you can open the template folder and edit the files
As per you request
Positioning is done in css file
And you can remove the crypto in html and js files
Let me know if you got it

**Comment by 0i0** [comment]
did you manage to modify it?
if so could you please close this issue?
